(function(){
  var GA4_ID="G-CTPML8CVML",CLARITY_ID="wu674xzdbf";
  function scoreBand(s){s=parseInt(s);if(isNaN(s)||s<0)return"unknown";if(s<=25)return"structural_failure";if(s<=50)return"fragile_franchise";if(s<=70)return"operationally_stable";if(s<=85)return"strategically_aligned";return"best_in_class";}
  function slugify(s){return(s||"unknown").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");}
  function initGA4(){window.dataLayer=window.dataLayer||[];window.gtag=window.gtag||function(){window.dataLayer.push(arguments);};gtag("js",new Date());gtag("config",GA4_ID,{send_page_view:false,anonymize_ip:true});var s=document.createElement("script");s.async=true;s.src="https://www.googletagmanager.com/gtag/js?id="+GA4_ID;document.head.appendChild(s);}
  function initClarity(){if(window.clarity)return;(function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);})(window,document,"clarity","script",CLARITY_ID);window.clarity("set","mask","all");}
  function track(n,p){p=p||{};if(typeof window.gtag==="function")gtag("event",n,p);if(typeof window.clarity==="function"){window.clarity("set","last_event",n);if(p.pfi_score_band)window.clarity("set","pfi_score_band",p.pfi_score_band);if(p.structural_pattern)window.clarity("set","structural_pattern",p.structural_pattern);}}
  function autoPageView(){var path=window.location.pathname.replace(/\/+$/,"").toLowerCase();var e="page_viewed";if(path===""||path==="/index"||path==="/index.html")e="home_viewed";else if(path.indexOf("payments-portfolio-diagnostic")!==-1||path==="/pfi"||path==="/pfi.html")e="pfi_page_viewed";else if(path==="/consulting"||path==="/consulting.html")e="consulting_page_viewed";track(e,{page_path:path});if(typeof window.gtag==="function")gtag("event","page_view",{page_title:document.title,page_location:window.location.href});}
  function wireContactClicks(){document.addEventListener("click",function(e){var el=e.target.closest("a,button");if(!el)return;var href=(el.getAttribute("href")||"").toLowerCase();var text=(el.innerText||el.textContent||"").trim().toLowerCase();if(href.indexOf("mailto:")===0||href.indexOf("/contact")!==-1||href.indexOf("#contact")!==-1||["contact","get in touch","reach out","book a call","schedule","let's talk"].some(function(k){return text.indexOf(k)!==-1;}))track("contact_clicked",{link_text:text.substring(0,80),link_type:href.indexOf("mailto:")===0?"email":"page"});});}
  window.CUA={scoreBand:scoreBand,pfiStarted:function(){track("pfi_started");},questionMilestone:function(n){n=parseInt(n);if(n===10)track("question_10_reached");if(n===20)track("question_20_reached");},pfiCompleted:function(score,label){track("pfi_completed",{pfi_score:parseInt(score)||0,pfi_score_band:scoreBand(score),structural_pattern:slugify(label)});if(typeof window.clarity==="function")window.clarity("set","pfi_completed","true");},pdfGenerated:function(score,label){track("pdf_generated",{pfi_score:parseInt(score)||0,pfi_score_band:scoreBand(score),structural_pattern:slugify(label)});}};
  function boot(){initGA4();initClarity();autoPageView();wireContactClicks();}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();
